Algoritmo "ESCOLHA"

Var
voto: inteiro

Inicio
Escreval("Digite seu voto:")
leia(voto)

Escolha voto
        caso 1
             Escreval("Você votou no Corinthians.")
        caso 2
             Escreval("Você votou no Flamengo.")
        caso 3
             Escreval("Você votou no São Paulo.")
        caso 4
             Escreval("Você votou no Botafogo-PB.")
        outrocaso
                 Escreval("Você votou nulo.")

fimescolha


Fimalgoritmo