Algoritmo "Trabalhando co tipos de vriáveis"
//

Var
// Seção de Declarações das variáveis 
nome: literal
sobrenome: literal
nomecompleto: literal
//   sobrenome: literal
//   nomecompleto: literal


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Informe seu nome:")
   leia(nome)
   Escreval("Escreva seu sobrenome:")
   leia(sobrenome)
   nomecompleto <- nome + "" + sobrenome
   escreval(nomecompleto)


Fimalgoritmo